[tox]
min_version = 4.0
env_list = lint, test
requires =
    tox-uv>=1.16

[testenv]
package = editable
runner = uv-venv-lock-runner
with_dev = true

[testenv:lint]
commands =
    black --check src tests
    isort --check-only src tests
    flake8 src tests
    mypy src tests

[testenv:test]
commands =
    pytest {posargs}
